create type "public"."section_type" as enum ('lecture', 'recitation', 'lab');

drop policy "Enable read access for all users" on "public"."lecture";

revoke delete on table "public"."lecture" from "anon";

revoke insert on table "public"."lecture" from "anon";

revoke references on table "public"."lecture" from "anon";

revoke select on table "public"."lecture" from "anon";

revoke trigger on table "public"."lecture" from "anon";

revoke truncate on table "public"."lecture" from "anon";

revoke update on table "public"."lecture" from "anon";

revoke delete on table "public"."lecture" from "authenticated";

revoke insert on table "public"."lecture" from "authenticated";

revoke references on table "public"."lecture" from "authenticated";

revoke select on table "public"."lecture" from "authenticated";

revoke trigger on table "public"."lecture" from "authenticated";

revoke truncate on table "public"."lecture" from "authenticated";

revoke update on table "public"."lecture" from "authenticated";

revoke delete on table "public"."lecture" from "service_role";

revoke insert on table "public"."lecture" from "service_role";

revoke references on table "public"."lecture" from "service_role";

revoke select on table "public"."lecture" from "service_role";

revoke trigger on table "public"."lecture" from "service_role";

revoke truncate on table "public"."lecture" from "service_role";

revoke update on table "public"."lecture" from "service_role";

alter table "public"."lecture" drop constraint "lecture_course_term_id_fkey";

alter table "public"."lecture" drop constraint "lecture_pkey";

drop index if exists "public"."lecture_pkey";

drop table "public"."lecture";


  create table "public"."section" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "section" text not null,
    "day" text not null,
    "start" time without time zone not null,
    "end" time without time zone not null,
    "location" text not null,
    "videoconference_link" text,
    "extra_info" text,
    "location_link" text,
    "course_term_id" text not null,
    "crn" integer not null default 0,
    "type" public.section_type not null default 'lecture'::public.section_type
      );


alter table "public"."section" enable row level security;


  create table "public"."section_leader" (
    "created_at" timestamp with time zone not null default now(),
    "section_id" bigint not null,
    "person_id" bigint not null
      );


alter table "public"."section_leader" enable row level security;

alter table "public"."topic" add column "section" bigint;

CREATE UNIQUE INDEX section_leader_pkey ON public.section_leader USING btree (section_id, person_id);

CREATE UNIQUE INDEX lecture_pkey ON public.section USING btree (id);

alter table "public"."section" add constraint "lecture_pkey" PRIMARY KEY using index "lecture_pkey";

alter table "public"."section_leader" add constraint "section_leader_pkey" PRIMARY KEY using index "section_leader_pkey";

alter table "public"."section" add constraint "lecture_course_term_id_fkey" FOREIGN KEY (course_term_id) REFERENCES public.course_term(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."section" validate constraint "lecture_course_term_id_fkey";

alter table "public"."section_leader" add constraint "section_leader_person_id_fkey" FOREIGN KEY (person_id) REFERENCES public.person(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."section_leader" validate constraint "section_leader_person_id_fkey";

alter table "public"."section_leader" add constraint "section_leader_section_id_fkey" FOREIGN KEY (section_id) REFERENCES public.section(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."section_leader" validate constraint "section_leader_section_id_fkey";

alter table "public"."topic" add constraint "topic_section_fkey" FOREIGN KEY (section) REFERENCES public.section(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."topic" validate constraint "topic_section_fkey";

grant delete on table "public"."section" to "anon";

grant insert on table "public"."section" to "anon";

grant references on table "public"."section" to "anon";

grant select on table "public"."section" to "anon";

grant trigger on table "public"."section" to "anon";

grant truncate on table "public"."section" to "anon";

grant update on table "public"."section" to "anon";

grant delete on table "public"."section" to "authenticated";

grant insert on table "public"."section" to "authenticated";

grant references on table "public"."section" to "authenticated";

grant select on table "public"."section" to "authenticated";

grant trigger on table "public"."section" to "authenticated";

grant truncate on table "public"."section" to "authenticated";

grant update on table "public"."section" to "authenticated";

grant delete on table "public"."section" to "service_role";

grant insert on table "public"."section" to "service_role";

grant references on table "public"."section" to "service_role";

grant select on table "public"."section" to "service_role";

grant trigger on table "public"."section" to "service_role";

grant truncate on table "public"."section" to "service_role";

grant update on table "public"."section" to "service_role";

grant delete on table "public"."section_leader" to "anon";

grant insert on table "public"."section_leader" to "anon";

grant references on table "public"."section_leader" to "anon";

grant select on table "public"."section_leader" to "anon";

grant trigger on table "public"."section_leader" to "anon";

grant truncate on table "public"."section_leader" to "anon";

grant update on table "public"."section_leader" to "anon";

grant delete on table "public"."section_leader" to "authenticated";

grant insert on table "public"."section_leader" to "authenticated";

grant references on table "public"."section_leader" to "authenticated";

grant select on table "public"."section_leader" to "authenticated";

grant trigger on table "public"."section_leader" to "authenticated";

grant truncate on table "public"."section_leader" to "authenticated";

grant update on table "public"."section_leader" to "authenticated";

grant delete on table "public"."section_leader" to "service_role";

grant insert on table "public"."section_leader" to "service_role";

grant references on table "public"."section_leader" to "service_role";

grant select on table "public"."section_leader" to "service_role";

grant trigger on table "public"."section_leader" to "service_role";

grant truncate on table "public"."section_leader" to "service_role";

grant update on table "public"."section_leader" to "service_role";


  create policy "Enable read access for all users"
  on "public"."section"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."section_leader"
  as permissive
  for select
  to public
using (true);




