
  create table "public"."assignment" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "description" text,
    "url" text not null,
    "due" timestamp without time zone,
    "notes" text[] not null default '{}'::text[],
    "assignment_group_id" bigint not null
      );


alter table "public"."assignment" enable row level security;


  create table "public"."assignment_group" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "description" text,
    "course_term_id" text not null
      );


alter table "public"."assignment_group" enable row level security;

alter table "public"."topic" alter column "materials" set default '{}'::jsonb[];

alter table "public"."topic" alter column "materials" set not null;

alter table "public"."topic" alter column "readings" set default '{}'::jsonb[];

alter table "public"."topic" alter column "readings" set not null;

CREATE UNIQUE INDEX assignment_group_pkey ON public.assignment_group USING btree (id);

CREATE UNIQUE INDEX assignment_pkey ON public.assignment USING btree (id);

alter table "public"."assignment" add constraint "assignment_pkey" PRIMARY KEY using index "assignment_pkey";

alter table "public"."assignment_group" add constraint "assignment_group_pkey" PRIMARY KEY using index "assignment_group_pkey";

alter table "public"."assignment" add constraint "assignment_assignment_group_id_fkey" FOREIGN KEY (assignment_group_id) REFERENCES public.assignment_group(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."assignment" validate constraint "assignment_assignment_group_id_fkey";

alter table "public"."assignment_group" add constraint "assignment_group_course_term_id_fkey" FOREIGN KEY (course_term_id) REFERENCES public.course_term(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."assignment_group" validate constraint "assignment_group_course_term_id_fkey";

grant delete on table "public"."assignment" to "anon";

grant insert on table "public"."assignment" to "anon";

grant references on table "public"."assignment" to "anon";

grant select on table "public"."assignment" to "anon";

grant trigger on table "public"."assignment" to "anon";

grant truncate on table "public"."assignment" to "anon";

grant update on table "public"."assignment" to "anon";

grant delete on table "public"."assignment" to "authenticated";

grant insert on table "public"."assignment" to "authenticated";

grant references on table "public"."assignment" to "authenticated";

grant select on table "public"."assignment" to "authenticated";

grant trigger on table "public"."assignment" to "authenticated";

grant truncate on table "public"."assignment" to "authenticated";

grant update on table "public"."assignment" to "authenticated";

grant delete on table "public"."assignment" to "service_role";

grant insert on table "public"."assignment" to "service_role";

grant references on table "public"."assignment" to "service_role";

grant select on table "public"."assignment" to "service_role";

grant trigger on table "public"."assignment" to "service_role";

grant truncate on table "public"."assignment" to "service_role";

grant update on table "public"."assignment" to "service_role";

grant delete on table "public"."assignment_group" to "anon";

grant insert on table "public"."assignment_group" to "anon";

grant references on table "public"."assignment_group" to "anon";

grant select on table "public"."assignment_group" to "anon";

grant trigger on table "public"."assignment_group" to "anon";

grant truncate on table "public"."assignment_group" to "anon";

grant update on table "public"."assignment_group" to "anon";

grant delete on table "public"."assignment_group" to "authenticated";

grant insert on table "public"."assignment_group" to "authenticated";

grant references on table "public"."assignment_group" to "authenticated";

grant select on table "public"."assignment_group" to "authenticated";

grant trigger on table "public"."assignment_group" to "authenticated";

grant truncate on table "public"."assignment_group" to "authenticated";

grant update on table "public"."assignment_group" to "authenticated";

grant delete on table "public"."assignment_group" to "service_role";

grant insert on table "public"."assignment_group" to "service_role";

grant references on table "public"."assignment_group" to "service_role";

grant select on table "public"."assignment_group" to "service_role";

grant trigger on table "public"."assignment_group" to "service_role";

grant truncate on table "public"."assignment_group" to "service_role";

grant update on table "public"."assignment_group" to "service_role";


  create policy "Enable read access for all users"
  on "public"."assignment"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."assignment_group"
  as permissive
  for select
  to public
using (true);




