alter type "public"."term" rename to "term__old_version_to_be_dropped";

create type "public"."term" as enum ('fall', 'winter', 'spring', 'summer');


  create table "public"."lecture" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "section" text not null,
    "day" text not null,
    "start" time without time zone not null,
    "end" time without time zone not null,
    "location" text not null,
    "videoconference_link" text,
    "extra_info" text,
    "location_link" text,
    "course_term_id" text not null,
    "crn" integer not null default 0
      );


alter table "public"."lecture" enable row level security;


  create table "public"."textbook" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "author" text,
    "link" text,
    "description" text,
    "course_term_id" text
      );


alter table "public"."textbook" enable row level security;

alter table "public"."course" drop column "terms";

alter table "public"."course_term" drop column "term";

drop type "public"."syllabus_category";

CREATE INDEX idx_hours_person_id ON public.hours USING btree (person_id);

CREATE UNIQUE INDEX lecture_pkey ON public.lecture USING btree (id);

CREATE UNIQUE INDEX textbook_pkey ON public.textbook USING btree (id);

alter table "public"."lecture" add constraint "lecture_pkey" PRIMARY KEY using index "lecture_pkey";

alter table "public"."textbook" add constraint "textbook_pkey" PRIMARY KEY using index "textbook_pkey";

alter table "public"."lecture" add constraint "lecture_course_term_id_fkey" FOREIGN KEY (course_term_id) REFERENCES public.course_term(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."lecture" validate constraint "lecture_course_term_id_fkey";

alter table "public"."textbook" add constraint "textbook_course_term_id_fkey" FOREIGN KEY (course_term_id) REFERENCES public.course_term(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."textbook" validate constraint "textbook_course_term_id_fkey";

grant delete on table "public"."lecture" to "anon";

grant insert on table "public"."lecture" to "anon";

grant references on table "public"."lecture" to "anon";

grant select on table "public"."lecture" to "anon";

grant trigger on table "public"."lecture" to "anon";

grant truncate on table "public"."lecture" to "anon";

grant update on table "public"."lecture" to "anon";

grant delete on table "public"."lecture" to "authenticated";

grant insert on table "public"."lecture" to "authenticated";

grant references on table "public"."lecture" to "authenticated";

grant select on table "public"."lecture" to "authenticated";

grant trigger on table "public"."lecture" to "authenticated";

grant truncate on table "public"."lecture" to "authenticated";

grant update on table "public"."lecture" to "authenticated";

grant delete on table "public"."lecture" to "service_role";

grant insert on table "public"."lecture" to "service_role";

grant references on table "public"."lecture" to "service_role";

grant select on table "public"."lecture" to "service_role";

grant trigger on table "public"."lecture" to "service_role";

grant truncate on table "public"."lecture" to "service_role";

grant update on table "public"."lecture" to "service_role";

grant delete on table "public"."textbook" to "anon";

grant insert on table "public"."textbook" to "anon";

grant references on table "public"."textbook" to "anon";

grant select on table "public"."textbook" to "anon";

grant trigger on table "public"."textbook" to "anon";

grant truncate on table "public"."textbook" to "anon";

grant update on table "public"."textbook" to "anon";

grant delete on table "public"."textbook" to "authenticated";

grant insert on table "public"."textbook" to "authenticated";

grant references on table "public"."textbook" to "authenticated";

grant select on table "public"."textbook" to "authenticated";

grant trigger on table "public"."textbook" to "authenticated";

grant truncate on table "public"."textbook" to "authenticated";

grant update on table "public"."textbook" to "authenticated";

grant delete on table "public"."textbook" to "service_role";

grant insert on table "public"."textbook" to "service_role";

grant references on table "public"."textbook" to "service_role";

grant select on table "public"."textbook" to "service_role";

grant trigger on table "public"."textbook" to "service_role";

grant truncate on table "public"."textbook" to "service_role";

grant update on table "public"."textbook" to "service_role";


  create policy "Enable read access for all users"
  on "public"."lecture"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."textbook"
  as permissive
  for select
  to public
using (true);
